#!/usr/bin/env bash
# Install nginx on your web-01,Nginx should be listening on port 80, When querying Nginx at its root / with a GET request using curl, it must return a page that contains the string Hello World!
apt-get update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
service nginx start 
