#!/usr/bin/env bash
# Install nginx on your web-01,Nginx should be listening on port 80, When querying Nginx at its root / with a GET request using curl, it must return a page that contains the string Hello World!
sudo apt update
sudo apt -y install nginx
sudo service nginx start 
echo "Hello World!" > /var/www/html/index.html
