#!/usr/bin/env bash
# install nginx on your web-01
sudo apt update
sudo apt -y install nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
