#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
sudo pt-get -y  update
sudo apt-get -y install nginx
sudo service nginx start
h="http {\n\tadd_header X-Served-By \"$HOSTNAME\";"
sudo sed -i "s/http {/$h/" /etc/nginx/nginx.conf
sudo service nginx restart
