#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
sudo apt-get update
sudo apt-get -y install ngin
sudo sed -i '19 i \\tadd_header X-Served-By $HOSTNAME;' /etc/nginx/nginx.conf
sudo service nginx restart
