#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt-get update
sudo apt-get install -y haproxy
sudo sed -i '10 i ENABLED=1' /etc/default/haproxy
sudo echo "
frontend server
    bind *:80
    mode http
    default_backend server_backend

backend server_backend
    balance roundrobin
    server 266295-web-01 52.21.57.114:80 check
    server 266295-web-02 3.85.177.230:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
