#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server. 
sudo apt-get -y update
sudo apt-get install -y haproxy
sudo echo "ENABLED=1" >> /etc/default/haproxy
sudo echo "
   frontend www
        bind *:80
        default_backend nginx_pool

   backend nginx_pool
        balance roundrobin
        mode http
        server 36581-web-01 34.232.53.239:80 check
        server 36581-web-02 18.206.206.128:80 check
" >> /etc/haproxy/haproxy.cfg
sudo haproxy -f /etc/haproxy/haproxy.cfg -c
sudo service haproxy restart
