#!/usr/bin/env bash
# a Bash script that generates a MySQL dump and creates a compressed archive out of it.
mysqldump -u root --password="$1" -A --events > backup.sql
file_name=$(date +"%d-%m-%Y")
tar -czvf "$file_name".tar.gz backup.sql
