#!/usr/bin/env bash
# This script is displaying "Best School" 10 times ,prints Hi at 9th line  on a new line.
i=0
while ((i < 10))
do
        echo "Best School"
        ((i++))
        if [ "$i" -eq 9 ]
        then
                echo "Hi"
        fi
done 
