#!/usr/bin/env bash
# a Bash script that displays the time for 12 hours and 59 minutes.
h=0
min=1
while ((h <= 12))
do
    echo "Hour: $h"
    ((h++))
    while ((min <= 59))
    do
        echo "$min"
        ((min++))
    done
    ((min = 1))
done
