#!/usr/bin/env bash
# a Bash script that displays:
# The content of the current directory.
# In a list format
# only the part of the name after the first dash is displayed. 

file_list=$(ls)
for i in $file_list
do
    echo "$i" | cut -d'-' -f 2
done
